pdoc/templates/css.mako

The `height: 100%;` is erroneous, as it gives the body an height which is 100% of that of the view-port, which is not relevant for a content which is to be scrollable. To see it, one may give the body a non-white background color, say orange (as an example), then scroll the content: the top has an orange and the rest of the scrollable content has a white (default) background.

Fix wrong HTML body height

---

pdoc/__init__.py

Without this patch, *pdoc* will filter-out variables whose values are an instance of a class defined in an imported package.
How to solve: remember *explicitly declared variables* by remembering the keys of `vardocs`, then in `__is_exported`, don't filter-out what may seems to be from another module and ends to be a variable whose value is an instance of a class declared in another module.

Avoid filtering out variables on their value

---

pdoc/__init__.py

Without this patch *pdoc* tries to import package's module as if there were submodules of modules as packages, for each package's modules.
Ex. if a package `P` contains modules `M1`, `M2`, `M3`, *pdoc* tries to import `P.M1.M1`, `P.M1.M2`, `P.M1.M3`, `P.M2.M1`, … and so on. This patch fix this, which I believe is an issue.

Avoid trying to import from non-existant packages

---

scripts/pdoc

`xrange` does not exist in Python 3, which have `range` only. Python 3 removed `range` from Python 2 and renamed `xrange` from Python 2 into `range`. See [What’s New In Python 3.0 / Views And Iterators Instead Of Lists](https://docs.python.org/3.0/whatsnew/3.0.html#views-and-iterators-instead-of-lists).

Fix for `xrange` and Python 3

---

scripts/pdoc

Command line option `--template-dir` was not propagated to pdoc subprocesses, causing `pdoc` to fail if options `--http` and `--template-dir` were combined. This patch fixes that.

Fixed --template-dir for http server.

---

scripts/pdoc

The fix introduced in dc57c4a1 doesn't work on Python 2 (because builtins isn't
always importable).  This commit attempts to shadow xrange with itself, and
falls back to range when it's not available (which accomplishes the same
thing).

fix Python 2 incompatibility

---

.gitignore

When installed with `pip install -e`, some files are generated.  These should
be ignored so that they aren't inadvertently checked in.

ignore files generated by development installs

---

pdoc/templates/html.mako

Removes a bug where it strips the first character of every line in the source code if you leave first line blank.

Remove html stripping bug from html.mako

---

doc/pdoc/index.html
pdoc/templates/html.mako

Use https for Google fonts

---

pdoc/__init__.py

In Py3, the filter() call creates an iterator which is exhausted by the
second call to search(). This was causing some methods to
nondeterministically not receive the inheritance annotation in the
generated docs.
Seems to fix #132

Fix inheritance labeling in Python 3

---

pdoc/cli.py
setup.py

This:
- Fixes Windows installs, including anaconda (it's not special in this regards). Having reviewed the issues, I believe this will fix #127, #123, #52 and #20.
- Should not affect Linux installs (but I can't test this unfortunately).
As in #127 you said you didn't use Python on Windows I'll try to explain:
Basically, the Windows install issue was down to using distutils' `scripts` argument in `setup.py` to create the CLI tool. This simply copies the named script into the Scripts folder on install. This didn't work on Windows as you ended up with a no-extension, non-executable file on your $PATH.
What this PR does instead is to use setuptools' `entry_points:console_scripts` feature, which is apparently now the preferred/cross-platform way to create CLI tools. Instead of just copying a …

Fix windows install

---

pdoc/templates/html.mako
setup.py

Among other things, this adds highlighting for the `async` keyword
The py3 lexer was added in [version 0.10](http://pygments.org/docs/lexers/#pygments.lexers.python.Python3Lexer)

Use Python 3 highlighter when ran in Python 3 environment

---

pdoc/templates/html.mako

Fixes https://github.com/BurntSushi/pdoc/issues/134
Replaces/Closes https://github.com/BurntSushi/pdoc/pull/122
See also:
http://docs.makotemplates.org/en/latest/unicode.html#specifying-the-encoding-of-a-template-file

Fix mako default encoding from ascii to utf-8

---

pdoc/__init__.py
pdoc/templates/html.mako

This change marks [asynchronous/coroutine functions](https://docs.python.org/3/reference/compound_stmts.html#async-def) as `async def` in the generated docs, since they're used and overridden differently than regular functions.
It should be backwards compatible with python < 3.5 as well.

Mark asynchronous functions as `async def`

---

pdoc/__init__.py

`cls` will always be in `cls`'s MRO, and so will `object` that everything inherits from. Hence, these two are redundant?
pdoc rocks; this is how Guido had imagined it! 😄

Only show *relevant* ancestors by pruning self and object from MRO

---

pdoc/cli.py
pdoc/doc.py
pdoc/extract.py
setup.cfg
test/modules/dirmod/__init__.py
test/modules/malformed/syntax.py
test/modules/one.py
test/packages/malformed_syntax.py
test/packages/simple.py
test/test_extract.py
test/test_pdoc.py

In modern Python this is much cleaner with importlib. Also remove special handling of PYTHONPATH 0 either the interpreter can discover the module, or we use a filesystem path, no other complications.

Revamp import and module extraction

---

MANIFEST.in

This allows a source package to be pip installed:
```
python3 setup.py sdist
pip install dist/pdoc-0.3.2.tar.gz
```

Add manifest file. Fixes #174

---

pdoc/templates/default/index.html.jinja2

The `replace`-method in JavaScript does only replace the first "." in the modulename. 
This does not work for modules with depth > 2 (e.g. `module.submodule.subsubmodule`, which would generate `href="module/submodule.subsubmodule.html"`.

fix wrong links in index.html

---

setup.py

Jinja 2.10.* included a bug that escaped the output of the `indent` function, see issue https://github.com/pallets/jinja/issues/823. This affects the default templates of pdoc, e.g. in the navigation for classes:
https://github.com/mitmproxy/pdoc/blob/d45f24ce73825e27a34f1165a068d6c6f1b420f6/pdoc/templates/default/module.html.jinja2#L580
This was fixed in Jinja2 with version 2.11.0 (see PR https://github.com/pallets/jinja/pull/826) (published January 2020), therefore I'd suggest to add 2.11.0 as the minimal required version to the setup.py to prevent the usage with older version.

require Jinja2 >= 2.11.0

---

CHANGELOG.md
pdoc/doc.py
test/test_doc.py

We don't use this for pdoc itself, but this can be quite useful to link to specific lines on GitHub etc.
@jedie: Is this API matching what you had in mind, or is there anything we can do make it more convenient?

Add `Doc.source_lines`

---

CHANGELOG.md
pdoc/docstrings.py

This PR allows google docstring sections to be parsed if they have multiple words in their headers, EG: "Instance Variables" or "Class Attributes".
Currently, custom headers can be added using the `pdoc.docstrings.GOOGLE_LIST_SECTIONS` constant but if the header contains mutliple words then it is ignored.
This is because I forgot to check whether multiple word headers worked when creating #266, I just assumed it would work like single word headers, so this should fix that.

 Allow google docstring section headers to contain spaces

---

pdoc/docstrings.py

This changes the Google docstring parser to match the first colon on the line rather than the last. This change means that this code:
```
Args:
my_list: A list which defaults to: a, b, c 
```
will be highlighted as "**my_list**: A list which defaults to: a, b, c"  instead of the current "**my_list: A list which defaults to**: a, b, c".
[Google's styleguide](https://google.github.io/styleguide/pyguide.html#doc-function-args) does not explicitly state what should happen when there are multiple colons, but the description of the syntax implies that the first colon is the significant one because `:` is not a valid character in a Python identifier.

Fix formatting on Google docstrings that have multiple colons

---

CHANGELOG.md
pdoc/_compat.py
pdoc/doc.py
pdoc/doc_ast.py
pdoc/doc_types.py
test/test_doc_ast.py
test/test_doc_types.py
test/test_snapshot.py
test/testdata/misc_py310.py
test/testdata/misc_py310.txt
test/testdata/misc_py39.html
test/testdata/misc_py39.py
test/testdata/misc_py39.txt
test/testdata/type_checking_imports.html
test/testdata/type_checking_imports.py
test/testdata/type_checking_imports.txt

This PR fixes #291. If pdoc cannot ordinarily resolve a forward reference type hint, it now tries to execute the contents of `if TYPE_CHECKING` or `if typing.TYPE_CHECKING` blocks in the current namespace before re-executing the forward reference.

Detect imports from TYPE_CHECKING blocks

---

CHANGELOG.md
pdoc/doc.py
pdoc/extract.py
test/testdata/misc.html
test/testdata/misc.py
test/testdata/misc.txt

Prefer epydoc-style docstrings after variable assignments over the variable's `__doc__`.

---

CHANGELOG.md
pdoc/__init__.py
pdoc/__main__.py
pdoc/_compat.py
pdoc/doc.py
pdoc/doc_types.py
pdoc/extract.py
pdoc/render_helpers.py
test/test_extract.py
test/test_main.py
test/testdata/flavors_google.html
test/testdata/flavors_numpy.html

A user can now add modules prefixed by a "!" to exclude them from the list of modules to process. 
Usage:
``` python
pdoc foo !foo.bar foo.bar.baz
```
Fixes #310

Add an option to ignore modules with a regex 

---

.github/workflows/main.yml
pdoc/_compat.py
pdoc/doc.py
pdoc/doc_types.py
test/test_doc_types.py
test/testdata/demo_eager.html
test/testdata/demo_eager.txt

`inspect.formatannotation` was [fixed][1] and it seems to have appeared in Python 3.10.1+. (Currently CI uses maximum 3.10.0).
I'm curious why snapshots have `x: list` annotations instead of `x: list[int]` if they use `formatannotation` from `doc_types.py` which have a fix :thinking:.
[1]: https://github.com/python/cpython/commit/d02ffd1b5c0fd8dec6dd2f7e3f2b0cfae48b7899

Skip test_formatannotation_still_unfixed test on Python >= 3.10.1

---

CHANGELOG.md
pdoc/doc.py
pdoc/docstrings.py
test/testdata/flavors_rst.html
test/testdata/flavors_rst.py
test/testdata/flavors_rst.txt

This PR adds support for field lists for reStructuredText docstrings. 😃 
(CC @talnagar)

Add support for rST field lists, refs #275

---

.github/workflows/main.yml
README.md
tox.ini

Codecov's new uploader cannot be used securely [1], so we take that opportunity to switch to something simpler.
[1] https://github.com/codecov/codecov-action/issues/574

Ditch Codecov

---

CHANGELOG.md
pdoc/templates/default/module.html.jinja2
test/testdata/demopackage.html
test/testdata/demopackage_dir.html

fixes #374 
Note, I haven't added functionality to keep the original verbose names. This PR forces the new format of short names.

shorten submodule text

---

CHANGELOG.md
pdoc/doc.py
pdoc/doc_pyi.py
test/test_doc_pyi.py
test/test_snapshot.py
test/testdata/type_stub.html
test/testdata/type_stub.py
test/testdata/type_stub.pyi
test/testdata/type_stub.txt

fixes https://github.com/mitmproxy/pdoc/issues/239

Add support for `.pyi` files

---

CHANGELOG.md
README.md
pdoc/__init__.py
pdoc/render_helpers.py

Born out of #401 this adds documentation describing what Markdown spec pdoc supports, why, and what additional extras are enabled.
Screenshots for the lazy:
As for the README I'm personally torn between using a footnote or just hyperlinking `Markdown` to the new doc section. I don't feel strongly one way or the other. You can see I tried a few variations in some commits. It's whatever you prefer!

Add "Markdown support" section to main docs

---

CHANGELOG.md
pdoc/doc.py
pdoc/templates/default/module.html.jinja2
test/test_snapshot.py
test/testdata/demo_long.html
test/testdata/demo_long.py
test/testdata/demo_long.txt

Document enum mebers without docstring

---

CHANGELOG.md
pdoc/docstrings.py
test/testdata/flavors_google.html
test/testdata/flavors_google.py
test/testdata/flavors_google.txt

This PR adds support for specifying alternative section names in Google docstrings that are to be interpreted as sections-of-lists, similarly to the standard "Args" section. Right now the PR aliases "Parameters" and "Params" to "Args"; these names are not standard but are often seen in the wild, especially in codebases that mix NumPy and Google-style docstrings (NumPy uses "Parameters" by default).
The PR could also partially fix the issue raised in https://github.com/mitmproxy/pdoc/issues/466 if we decided to add "Keyword Arguments" and "Keyword Args" such that "Keyword Args" is handled as-is and "Keyword Arguments" is aliased to "Keyword Args". That would require an additional commit that I'm happy to do if the maintainer agrees with the general direction of this PR.

Add support for alternative section names in Google docstrings

---

CHANGELOG.md
pdoc/_compat.py

Don't bork on `typing_extensions.Literal`

---

CHANGELOG.md
pdoc/doc.py
pdoc/doc_ast.py
pdoc/markdown2/__init__.py
test/testdata/misc.html
test/testdata/misc.py
test/testdata/misc.txt

Fix rendering of dynamically modified docstrings

---

CHANGELOG.md
pdoc/web.py
test/test_web.py

refs https://github.com/mitmproxy/pdoc/issues/615

Be more strict when parsing URLs

---

CHANGELOG.md
pdoc/docstrings.py

Added simple parsing of `code-block` ReST directives, mainly for compatibility purposes with Sphinx. While in Sphinx there seem to be multiple options for writing down blocks of code, the `code-block` one looks like the one which is, structure-wise, the most similar to Markdown's triple backticks.

Added parsing of `code-block` ReST directives

---

pdoc/__main__.py
pdoc/search.py

docs: mention that search is only active for 2+ pages

---

CHANGELOG.md
pdoc/doc.py
pdoc/doc_ast.py
test/test_doc.py

I added a function get_source_file to doc_ast.py that tries to get the source file from obj.__wrapped__ if inspect.getsourcefile(obj) doesn't succeed.
I used the same cached approach as in doc_ast.get_source.
closes #656

get source_file of wrapped functions

---

CHANGELOG.md
pdoc/doc_pyi.py

Add support for stub-only package.
The typehints for the package `flyingcircus` could be in the `flyingcircus-stubs` package.

Support PEP-0561 compatible stub-only packages

---

CHANGELOG.md
pdoc/templates/math.html.jinja2
test/testdata/math_demo.html
test/testdata/math_misc.html

closes #674 
Adds `overflow-y:hidden` to the mathjax container template CSS.
This removes unnesisary vertical scroll bars that show up in Chrome and Edge when `overflow-x` is set to `auto`, particularly for multi-line display mode math blocks.
<details>
<summary>Click Here to expand source code for images below</summary>
`test_module.py`:
```python
r"""
this is an $i=n$ line math expression
Long (always needs horizontal scroll)
$$
5a^3b^2 - 2b^4c + 7c^2d^3e - 3d^2ef^2 + 6e^3f - 4a^2f^3 + 9a^4bc^2 - 8b^3d^2e^2 + 3c^5de - 7d^3e^4f + 2a^2b^2c^3 - 6b^5df^2 + 4c^3d^4e^2 - 9d^2e^3f^3 + 5a^3cf^4 - 2b^2d^5e + 8c^4d^2f - 6a^5be^3 + 7b^3c^2d^3
$$
Short (never needs scroll)
$$
5a^3b^2 - 2b^4c + 7c^2d^3e - 3d^2ef^2
$$
$$
\\begin{align}
2x^2 + 3y - 7z &= 5 \\\\
11 &= 4x - 6y^3 + 2z^2 + 5a^3b^2 - 2b^4c …
```

add overflow-y: hidden to mathjax containers

---

CHANGELOG.md
pdoc/doc_pyi.py
test/test_snapshot.py
test/testdata/type_stubs.html
test/testdata/type_stubs.txt
test/testdata/type_stubs/__init__.py
test/testdata/type_stubs/__init__.pyi
test/testdata/type_stubs/_utils.py
test/testdata/type_stubs/_utils.pyi

refs https://github.com/mitmproxy/pdoc/issues/731
@apparebit: Could you please check if this fixes your issue? I've tried following your repro steps, but this fails when running `./rr.sh` the second time (maturin: not found).

Improve pyi file import

---

pdoc/doc.py
test/test_smoke.py

Resolve the `TypeError` by testing for the `__contains__` attribute

fix(#753): API documentation for `unittest.mock`

---

docs/index.html.jinja2

This PR updates the URL of the Google usage example at the foot of `https://pdoc.dev/` to new location at `https://or-tools.github.io/docs/pdoc/`.

docs: correct link to Google usage example

---

pdoc/templates/mermaid.html.jinja2
test/testdata/mermaid_demo.html

I discovered your product and it is awesome. However noticed that mermaid (one of the awesome features you provide) is on `v10`. This will bring it up to `v11`. In the tests I ran for rendering mermaid documents it supports the upgraded mermaid syntax / styling.

Update CDN location of mermaid from v10 to v11

---

pdoc/render_helpers.py

Markup is a sub-class of str, so this wasn't strictly *wrong*, but it's more correct this way and clearer when extending these filters.

Fix Markup-returning functions' return type

---

pdoc/doc_types.py

The actual import is correct at the top of this one same file.

fix tiny mistake in warning message

---

pdoc/doc.py

Trying to use `pdoc -o` instead of `pdoc` in my project caused a long stacktrace with this error at the end:
File "/Users/feuh/.../.venv/lib/python3.12/site-packages/pdoc/doc.py", line 640, in _var_annotations
_safe_getattr(cls, "__module__", "") + "." + cls.__qualname__
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
This was caused by one class' `__module__` attribute being `None`.
I could not find the reason why that happens and why it happens only when using `-o`, but this change ensures it won't be a problem again.

Fix TypeError when cls.__module__ is None

---

CHANGELOG.md
pdoc/web.py
test/test_web.py

Fix improper handling of URL-escaped module names

---

CHANGELOG.md
pdoc/render_helpers.py
test/test_render_helpers.py

This enables markdown2's `mixed=True` setting of the header-ids extra.
Closes #805.

feat: enable mixed markdown and HTML header IDs
